
FROM gcr.io/distroless/cc-debian10:nonroot

COPY --chown=nonroot:nonroot ./server /home/nonroot/server

ENTRYPOINT [ "/home/nonroot/server/Rabies_ANGD/Binaries/Linux/Rabies_ANGDServer", "Rabies_ANGD"]
